server:
  port: 8088

spring:
  datasource:                               # 数据源相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 1
    host: 192.168.196.128
    port: 6379
    password: yuseven

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl